name: continuous integration

on:
  push:
    branches:
      - master
      - main
      - feature/**
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: build Docker file
        uses: docker/build-push-action@v2
        with:
          push: false
