name: release
on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v2

      - id: determine-tag
        name: Determine Docker tag
        run: echo "::set-output name=tag::$(date +%Y-%m-%d)"

      - name: build Docker file
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/arm64, linux/amd64
          tags: |
            ghcr.io/observabilitystack/s3_exporter:${{ steps.determine-tag.outputs.tag }}
            ghcr.io/observabilitystack/s3_exporter:latest
            observabilitystack/s3_exporter:${{ steps.determine-tag.outputs.tag }}
            observabilitystack/s3_exporter:latest
